import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_auth/firebase_auth.dart';

class LocalizationService extends Translations {
  // Default locale
  static const locale = Locale('en', 'US');

  // Fallback locale
  static const fallbackLocale = Locale('en', 'US');

  // Supported languages
  static final langs = ['English', 'Urdu', 'Arabic', 'Spanish'];

  // Supported locales
  static final locales = [
    const Locale('en', 'US'),
    const Locale('ur', 'PK'),
    const Locale('ar', 'AE'),
    const Locale('es', 'ES'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'expenses': 'Expenses',
      'statistics': 'Statistics',
      'profile': 'Profile',
      'transactions': 'Transactions',
      'reports': 'Reports',
      'settings': 'Settings',
      'language': 'Language',
      'biometric_lock': 'Biometric Lock',
      'backup_data': 'Backup Data',
      'restore_data': 'Restore Data',
      'see_all': 'See all',
      'no_note': 'No note',
      'tap_to_change': 'Tap to change',
      'spending_by_category': 'Spending by Category',
      'no_expense_data': 'No expense data for chart',
      'logout': 'Logout',
      'good_afternoon': 'Good afternoon',
      'user': 'User',
      'password': 'Password',
      'bug_report': 'Bug report & Feedback',
      'rate_us': 'Rate us on Google Play',
      'share_with_friends': 'Share with friends',
      'privacy_policy': 'Privacy Policy',
      'security': 'Security',
      'data_management': 'Data Management',
      'select_language': 'Select Language',
      'home': 'Home',
      'edit': 'Edit',
      'wallets': 'Wallets',
      'budgets': 'Budgets',
      'no_wallets_added': 'No Wallets Added',
      'delete_wallet': 'Delete Wallet',
      'delete_confirm': 'Are you sure you want to delete this?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'default_budget': 'Default Budget',
      'remaining': 'Remaining',
      'of': 'of',
      'notifications': 'Notifications',
      'clear_all': 'Clear all',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'no_notifications': 'No Notifications Yet',
      'notification_description':
          'You\'ll see wallet & budget alerts here once they are triggered.',
      'clear_confirm_title': 'Clear All Notifications',
      'clear_confirm_body':
          'This will permanently remove all notification history.',
      // Categories
      'Salary': 'Salary',
      'Freelance': 'Freelance',
      'Investment': 'Investment',
      'Business': 'Business',
      'Pocket Money': 'Pocket Money',
      'Rent Income': 'Rent Income',
      'Gifts': 'Gifts',
      'Bonus': 'Bonus',
      'Other Income': 'Other Income',
      'Food & Drink': 'Food & Drink',
      'Shopping': 'Shopping',
      'Transportation': 'Transportation',
      'Rent': 'Rent',
      'Groceries': 'Groceries',
      'Fuel': 'Fuel',
      'Entertainment': 'Entertainment',
      'Health & Fitness': 'Health & Fitness',
      'Utilities': 'Utilities',
      'Subscriptions': 'Subscriptions',
      'Education': 'Education',
      'Other Expense': 'Other Expense',
      // Wallets
      'Cash': 'Cash',
      'Bank Account': 'Bank Account',
      'Credit Card': 'Credit Card',
      'Savings': 'Savings',
      'Paypal': 'Paypal',
      'Digital Wallet': 'Digital Wallet',
      'Crypto': 'Crypto',
      // Budgets
      'Monthly': 'Monthly',
      'Weekly': 'Weekly',
      'Travel': 'Travel',
      'Custom': 'Custom',
      // Repeat Types
      'Every day': 'Every day',
      'Every 2 days': 'Every 2 days',
      'Every work day': 'Every work day',
      'Every week': 'Every week',
      'Every 2 weeks': 'Every 2 weeks',
      'Every 4 weeks': 'Every 4 weeks',
      'Every month': 'Every month',
      'Every 2 months': 'Every 2 months',
      'Every 4 months': 'Every 4 months',
      'edit_transaction': 'Edit Transaction',
      'add_transaction': 'Add Transaction',
      'how_much': 'How much?',
      'category': 'Category',
      'wallet': 'Wallet',
      'budget': 'Budget',
      'note': 'Note',
      'enter_here': 'Enter here',
      'add_attachment': 'Add attachment',
      'repeat': 'Repeat',
      'repeat_transaction': 'Repeat transaction',
      'update_transaction': 'Update Transaction',
      'add_income': 'Add Income',
      'add_expense': 'Add Expense',
      'select': 'Select',
      'transaction_details': 'Transaction Details',
      'delete_transaction_confirm':
          'Are you sure you want to delete this transaction?',
      'type': 'Type',
      'date': 'Date',
      'attachment': 'Attachment',
      'image_not_found': 'Image not found',
      'no_note_added': 'No note added',
      'Income': 'Income',
      'Expense': 'Expense',
      'transaction_history': 'Transaction History',
      'no_income_yet': 'No income transactions yet',
      'no_expense_yet': 'No expense transactions yet',
      'update_wallet': 'Update Wallet',
      'create_wallet': 'Create Wallet',
      'balance': 'Balance',
      'receive_alert': 'Receive Alert',
      'receive_alert_desc': 'Receive alert when it reaches\nsome point.',
      'update_budget': 'Update Budget',
      'create_budget': 'Create Budget',
      'how_much_spend': 'How much do you want to spend?',
      'financial_reports': 'Financial Reports',
      'select_report_period': 'Select Report Period',
      'summary': 'Summary',
      'export_pdf': 'Export to PDF',
      'This Week': 'This Week',
      'This Month': 'This Month',
      'This Year': 'This Year',
      'All Time': 'All Time',
    },
    'ur_PK': {
      'total_balance': 'کل بیلنس',
      'income': 'آمدنی',
      'expense': 'اخراجات',
      'expenses': 'اخراجات',
      'statistics': 'اعداد و شمار',
      'profile': 'پروفائل',
      'transactions': 'لین دین',
      'reports': 'رپورٹس',
      'settings': 'ترتیبات',
      'language': 'زبان',
      'biometric_lock': 'بائیو میٹرک لاک',
      'backup_data': 'بیک اپ ڈیٹا',
      'restore_data': 'ڈیٹا بحال کریں',
      'see_all': 'سب دیکھیں',
      'no_note': 'کوئی نوٹ نہیں',
      'tap_to_change': 'تبدیل کرنے کے لیے تھپتھپائیں',
      'spending_by_category': 'زمرہ کے لحاظ سے اخراجات',
      'no_expense_data': 'چارٹ کے لیے کوئی ڈیٹا نہیں ہے',
      'logout': 'لاگ آؤٹ',
      'good_afternoon': 'سہ پہر بخیر',
      'user': 'صارف',
      'password': 'پاس ورڈ',
      'bug_report': 'بگ رپورٹ اور فیڈ بیک',
      'rate_us': 'ہمیں گوگل پلے پر ریٹ کریں',
      'share_with_friends': 'دوستوں کے ساتھ شیئر کریں',
      'privacy_policy': 'پرائیویسی پالیسی',
      'security': 'سیکورٹی',
      'data_management': 'ڈیٹا مینجمنٹ',
      'select_language': 'زبان منتخب کریں',
      'home': 'ہوم',
      'edit': 'ترمیم',
      'wallets': 'والٹس',
      'budgets': 'بجٹ',
      'no_wallets_added': 'کوئی والٹ شامل نہیں ہے',
      'delete_wallet': 'والٹ حذف کریں',
      'delete_confirm': 'کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'default_budget': 'ڈیفالٹ بجٹ',
      'remaining': 'باقی',
      'of': 'میں سے',
      'notifications': 'اطلاعات',
      'clear_all': 'سب صاف کریں',
      'today': 'آج',
      'yesterday': 'کل',
      'no_notifications': 'ابھی تک کوئی اطلاع نہیں ہے',
      'notification_description':
          'والٹ اور بجٹ الرٹس یہاں ظاہر ہوں گے جب وہ ٹرگر ہوں گے۔',
      'clear_confirm_title': 'تمام اطلاعات صاف کریں',
      'clear_confirm_body':
          'یہ تمام اطلاعات کی سرگزشت کو مستقل طور پر ختم کر دے گا۔',
      // Categories
      'Salary': 'تنخواہ',
      'Freelance': 'فری لانس',
      'Investment': 'سرمایہ کاری',
      'Business': 'کاروبار',
      'Pocket Money': 'جیب خرچ',
      'Rent Income': 'کرایہ کی آمدنی',
      'Gifts': 'تحائف',
      'Bonus': 'بونس',
      'Other Income': 'دیگر آمدنی',
      'Food & Drink': 'کھانا پینا',
      'Shopping': 'شاپنگ',
      'Transportation': 'آمد و رفت',
      'Rent': 'کرایہ',
      'Groceries': 'کریانہ',
      'Fuel': 'ایندھن',
      'Entertainment': 'تفریح',
      'Health & Fitness': 'صحت اور فٹنس',
      'Utilities': 'یوٹیلیٹیز',
      'Subscriptions': 'سبسکرپشنز',
      'Education': 'تعلیم',
      'Other Expense': 'دیگر اخراجات',
      // Wallets
      'Cash': 'نقد',
      'Bank Account': 'بینک اکاؤنٹ',
      'Credit Card': 'کریڈٹ کارڈ',
      'Savings': 'بچت',
      'Paypal': 'پے پال',
      'Digital Wallet': 'ڈیجیٹل والٹ',
      'Crypto': 'کرپٹو',
      // Budgets
      'Monthly': 'ماہانہ',
      'Weekly': 'ہفتہ وار',
      'Travel': 'سفر',
      'Custom': 'حسب ضرورت',
      // Repeat Types
      'Every day': 'ہر روز',
      'Every 2 days': 'ہر 2 دن بعد',
      'Every work day': 'ہر کام کے دن',
      'Every week': 'ہر ہفتے',
      'Every 2 weeks': 'ہر 2 ہفتے بعد',
      'Every 4 weeks': 'ہر 4 ہفتے بعد',
      'Every month': 'ہر ماہ',
      'Every 2 months': 'ہر 2 ماہ بعد',
      'Every 4 months': 'ہر 4 ماہ بعد',
      'edit_transaction': 'لین دین میں ترمیم کریں',
      'add_transaction': 'لین دین شامل کریں',
      'how_much': 'کتنا؟',
      'category': 'زمرہ',
      'wallet': 'والٹ',
      'budget': 'بجٹ',
      'note': 'نوٹ',
      'enter_here': 'یہاں درج کریں',
      'add_attachment': 'منسلکہ شامل کریں',
      'repeat': 'دہرائیں',
      'repeat_transaction': 'لین دین کو دہرائیں',
      'update_transaction': 'لین دین کو اپ ڈیٹ کریں',
      'add_income': 'آمدنی شامل کریں',
      'add_expense': 'اخراجات شامل کریں',
      'select': 'منتخب کریں',
      'transaction_details': 'لین دین کی تفصیلات',
      'delete_transaction_confirm':
          'کیا آپ واقعی اس لین دین کو حذف کرنا چاہتے ہیں؟',
      'type': 'قسم',
      'date': 'تاریخ',
      'attachment': 'منسلکہ',
      'image_not_found': 'تصویر نہیں ملی',
      'no_note_added': 'کوئی نوٹ شامل نہیں کیا گیا',
      'Income': 'آمدنی',
      'Expense': 'اخراجات',
      'transaction_history': 'لین دین کی تاریخ',
      'no_income_yet': 'ابھی تک کوئی آمدنی کا لین دین نہیں ہے',
      'no_expense_yet': 'ابھی تک کوئی اخراجات کا لین دین نہیں ہے',
      'update_wallet': 'والٹ اپ ڈیٹ کریں',
      'create_wallet': 'والٹ بنائیں',
      'balance': 'بیلنس',
      'receive_alert': 'الرٹ موصول کریں',
      'receive_alert_desc':
          'جب یہ کسی خاص مقام پر پہنچ جائے تو الرٹ موصول کریں۔',
      'update_budget': 'بجٹ اپ ڈیٹ کریں',
      'create_budget': 'بجٹ بنائیں',
      'how_much_spend': 'آپ کتنا خرچ کرنا چاہتے ہیں؟',
      'financial_reports': 'مالیاتی رپورٹس',
      'select_report_period': 'رپورٹ کی مدت منتخب کریں',
      'summary': 'خلاصہ',
      'export_pdf': 'PDF میں ایکسپورٹ کریں',
      'This Week': 'اس ہفتے',
      'This Month': 'اس ماہ',
      'This Year': 'اس سال',
      'All Time': 'تمام وقت',
    },
    'ar_AE': {
      'total_balance': 'إجمالي الرصيد',
      'income': 'دخل',
      'expense': 'مصروف',
      'expenses': 'مصاريف',
      'statistics': 'إحصائيات',
      'profile': 'الملف الشخصي',
      'transactions': 'المعاملات',
      'reports': 'تقارير',
      'settings': 'إعدادات',
      'language': 'لغة',
      'biometric_lock': 'قفل بصمة الإصبع',
      'backup_data': 'نسخ البيانات احتياطياً',
      'restore_data': 'استعادة البيانات',
      'see_all': 'عرض الكل',
      'no_note': 'لا توجد ملاحظة',
      'tap_to_change': 'انقر للتغيير',
      'spending_by_category': 'الإنفاق حسب الفئة',
      'no_expense_data': 'لا توجد بيانات مصروفات للمخطط',
      'logout': 'تسجيل الخروج',
      'good_afternoon': 'مساء الخير',
      'user': 'مستخدم',
      'password': 'كلمة المرور',
      'bug_report': 'تقرير الأخطاء والملاحظات',
      'rate_us': 'قيمنا على جوجل بلاي',
      'share_with_friends': 'شارك مع الأصدقاء',
      'privacy_policy': 'سياسة الخصوصية',
      'security': 'أمان',
      'data_management': 'إدارة البيانات',
      'select_language': 'اختر اللغة',
      'home': 'الرئيسية',
      'edit': 'تعديل',
      'wallets': 'محافظ',
      'budgets': 'ميزانيات',
      'no_wallets_added': 'لم يتم إضافة محافظ',
      'delete_wallet': 'حذف المحفظة',
      'delete_confirm': 'هل أنت متأكد أنك تريد حذف هذا؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'default_budget': 'الميزانية الافتراضية',
      'remaining': 'متبقي',
      'of': 'من',
      'notifications': 'إشعارات',
      'clear_all': 'مسح الكل',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'no_notifications': 'لا توجد إشعارات بعد',
      'notification_description':
          'سترى تنبيهات المحفظة والميزانية هنا بمجرد تفعيلها.',
      'clear_confirm_title': 'مسح جميع الإشعارات',
      'clear_confirm_body': 'سيؤدي هذا إلى إزالة جميع سجل الإشعارات بشكل دائم.',
      // Categories
      'Salary': 'راتب',
      'Freelance': 'عمل حر',
      'Investment': 'استثمار',
      'Business': 'أعمال',
      'Pocket Money': 'مصروف جيب',
      'Rent Income': 'دخل الإيجار',
      'Gifts': 'هدايا',
      'Bonus': 'مكافأة',
      'Other Income': 'دخل آخر',
      'Food & Drink': 'طعام وشراب',
      'Shopping': 'تسوق',
      'Transportation': 'مواصلات',
      'Rent': 'إيجار',
      'Groceries': 'بقالة',
      'Fuel': 'وقود',
      'Entertainment': 'ترفيه',
      'Health & Fitness': 'صحة ولياقة',
      'Utilities': 'خدمات عامة',
      'Subscriptions': 'اشتراكات',
      'Education': 'تعليم',
      'Other Expense': 'مصروف آخر',
      // Wallets
      'Cash': 'نقد',
      'Bank Account': 'حساب بنكي',
      'Credit Card': 'بطاقة ائتمان',
      'Savings': 'مدخرات',
      'Paypal': 'بايبال',
      'Digital Wallet': 'محفظة رقمية',
      'Crypto': 'كريبتو',
      // Budgets
      'Monthly': 'شهري',
      'Weekly': 'أسبوعي',
      'Travel': 'سفر',
      'Custom': 'مخصص',
      // Repeat Types
      'Every day': 'كل يوم',
      'Every 2 days': 'كل يومين',
      'Every work day': 'كل يوم عمل',
      'Every week': 'كل أسبوع',
      'Every 2 weeks': 'كل أسبوعين',
      'Every 4 weeks': 'كل 4 أسابيع',
      'Every month': 'كل شهر',
      'Every 2 months': 'كل شهرين',
      'Every 4 months': 'كل 4 أشهر',
      'edit_transaction': 'تعديل المعاملة',
      'add_transaction': 'إضافة معاملة',
      'how_much': 'كم المبلغ؟',
      'category': 'فئة',
      'wallet': 'محفظة',
      'budget': 'ميزانية',
      'note': 'ملاحظة',
      'enter_here': 'أدخل هنا',
      'add_attachment': 'إضافة مرفق',
      'repeat': 'تكرار',
      'repeat_transaction': 'تكرار المعاملة',
      'update_transaction': 'تحديث المعاملة',
      'add_income': 'إضافة دخل',
      'add_expense': 'إضافة مصروف',
      'select': 'اختر',
      'transaction_details': 'تفاصيل المعاملة',
      'delete_transaction_confirm': 'هل أنت متأكد أنك تريد حذف هذه المعاملة؟',
      'type': 'نوع',
      'date': 'تاريخ',
      'attachment': 'مرفق',
      'image_not_found': 'الصورة غير موجودة',
      'no_note_added': 'لم يتم إضافة ملاحظة',
      'Income': 'دخل',
      'Expense': 'مصروف',
      'transaction_history': 'تاريخ المعاملات',
      'no_income_yet': 'لا توجد معاملات دخل بعد',
      'no_expense_yet': 'لا توجد معاملات مصروف بعد',
      'update_wallet': 'تحديث المحفظة',
      'create_wallet': 'إنشاء محفظة',
      'balance': 'رصيد',
      'receive_alert': 'تلقي تنبيه',
      'receive_alert_desc': 'تلقي تنبيه عندما يصل إلى\nنقطة معينة.',
      'update_budget': 'تحديث الميزانية',
      'create_budget': 'إنشاء ميزانية',
      'how_much_spend': 'كم تريد أن تنفق؟',
      'financial_reports': 'التقارير المالية',
      'select_report_period': 'اختر فترة التقرير',
      'summary': 'ملخص',
      'export_pdf': 'تصدير إلى PDF',
      'This Week': 'هذا الأسبوع',
      'This Month': 'هذا الشهر',
      'This Year': 'هذه السنة',
      'All Time': 'كل الوقت',
    },
    'es_ES': {
      'total_balance': 'Balance Total',
      'income': 'Ingresos',
      'expense': 'Gastos',
      'expenses': 'Gastos',
      'statistics': 'Estadísticas',
      'profile': 'Perfil',
      'transactions': 'Transacciones',
      'reports': 'Informes',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'biometric_lock': 'Bloqueo biométrico',
      'backup_data': 'Copia de seguridad',
      'restore_data': 'Restaurar datos',
      'see_all': 'Ver todo',
      'no_note': 'Sin nota',
      'tap_to_change': 'Toca para cambiar',
      'spending_by_category': 'Gastos por categoría',
      'no_expense_data': 'No hay datos de gastos',
      'logout': 'Cerrar sesión',
      'good_afternoon': 'Buenas tardes',
      'user': 'Usuario',
      'password': 'Contraseña',
      'bug_report': 'Reporte de errores y comentarios',
      'rate_us': 'Califícanos en Google Play',
      'share_with_friends': 'Compartir con amigos',
      'privacy_policy': 'Política de privacidad',
      'security': 'Seguridad',
      'data_management': 'Gestión de datos',
      'select_language': 'Seleccionar idioma',
      'home': 'Inicio',
      'edit': 'Editar',
      'wallets': 'Billeteras',
      'budgets': 'Presupuestos',
      'no_wallets_added': 'No se agregaron billeteras',
      'delete_wallet': 'Eliminar billetera',
      'delete_confirm': '¿Estás seguro de que quieres eliminar esto?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'default_budget': 'Presupuesto predeterminado',
      'remaining': 'Restante',
      'of': 'de',
      'notifications': 'Notificaciones',
      'clear_all': 'Limpiar todo',
      'today': 'Hoy',
      'yesterday': 'Ayer',
      'no_notifications': 'No hay notificaciones aún',
      'notification_description':
          'Verás las alertas de billetera y presupuesto aquí una vez que se activen.',
      'clear_confirm_title': 'Borrar todas las notificaciones',
      'clear_confirm_body':
          'Esto eliminará permanentemente todo el historial de notificaciones.',
      // Categories
      'Salary': 'Salario',
      'Freelance': 'Freelance',
      'Investment': 'Inversión',
      'Business': 'Negocios',
      'Pocket Money': 'Dinero de bolsillo',
      'Rent Income': 'Ingresos por alquiler',
      'Gifts': 'Regalos',
      'Bonus': 'Bono',
      'Other Income': 'Otros ingresos',
      'Food & Drink': 'Comida y bebida',
      'Shopping': 'Compras',
      'Transportation': 'Transporte',
      'Rent': 'Alquiler',
      'Groceries': 'Comestibles',
      'Fuel': 'Combustible',
      'Entertainment': 'Entretenimiento',
      'Health & Fitness': 'Salud y fitness',
      'Utilities': 'Servicios públicos',
      'Subscriptions': 'Suscripciones',
      'Education': 'Educación',
      'Other Expense': 'Otros gastos',
      // Wallets
      'Cash': 'Efectivo',
      'Bank Account': 'Cuenta bancaria',
      'Credit Card': 'Tarjeta de crédito',
      'Savings': 'Ahorros',
      'Paypal': 'Paypal',
      'Digital Wallet': 'Billetera digital',
      'Crypto': 'Crypto',
      // Budgets
      'Monthly': 'Mensual',
      'Weekly': 'Semanal',
      'Travel': 'Viajes',
      'Custom': 'Personalizado',
      // Repeat Types
      'Every day': 'Cada día',
      'Every 2 days': 'Cada 2 días',
      'Every work day': 'Cada día laborable',
      'Every week': 'Cada semana',
      'Every 2 weeks': 'Cada 2 semanas',
      'Every 4 weeks': 'Cada 4 semanas',
      'Every month': 'Cada mes',
      'Every 2 months': 'Cada 2 meses',
      'Every 4 months': 'Cada 4 meses',
      'edit_transaction': 'Editar transacción',
      'add_transaction': 'Agregar transacción',
      'how_much': '¿Cuánto?',
      'category': 'Categoría',
      'wallet': 'Billetera',
      'budget': 'Presupuesto',
      'note': 'Nota',
      'enter_here': 'Ingrese aquí',
      'add_attachment': 'Agregar adjunto',
      'repeat': 'Repetir',
      'repeat_transaction': 'Repetir transacción',
      'update_transaction': 'Actualizar transacción',
      'add_income': 'Agregar ingreso',
      'add_expense': 'Agregar gasto',
      'select': 'Seleccionar',
      'transaction_details': 'Detalles de la transacción',
      'delete_transaction_confirm':
          '¿Estás seguro de que quieres eliminar esta transacción?',
      'type': 'Tipo',
      'date': 'Fecha',
      'attachment': 'Adjunto',
      'image_not_found': 'Imagen no encontrada',
      'no_note_added': 'No se agregó nota',
      'Income': 'Ingreso',
      'Expense': 'Gasto',
      'transaction_history': 'Historial de transacciones',
      'no_income_yet': 'Aún no hay transacciones de ingresos',
      'no_expense_yet': 'Aún no hay transacciones de gastos',
      'update_wallet': 'Actualizar billetera',
      'create_wallet': 'Crear billetera',
      'balance': 'Balance',
      'receive_alert': 'Recibir alerta',
      'receive_alert_desc': 'Recibir alerta cuando llegue a\nalgún punto.',
      'update_budget': 'Actualizar presupuesto',
      'create_budget': 'Crear presupuesto',
      'how_much_spend': '¿Cuánto quieres gastar?',
      'financial_reports': 'Informes financieros',
      'select_report_period': 'Seleccionar período del informe',
      'summary': 'Resumen',
      'export_pdf': 'Exportar a PDF',
      'This Week': 'Esta semana',
      'This Month': 'Este mes',
      'This Year': 'Este año',
      'All Time': 'Todo el tiempo',
    },
  };

  // Logic to change language
  static void changeLocale(String lang) async {
    final locale = getLocaleFromLang(lang);
    Get.updateLocale(locale);

    // Save to Hive
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid != null) {
      final box = await Hive.openBox('settings_$uid');
      await box.put('language', lang);
    }
  }

  static Locale getLocaleFromLang(String lang) {
    for (int i = 0; i < langs.length; i++) {
      if (lang == langs[i]) return locales[i];
    }
    return Get.locale ?? locale;
  }

  static Locale getCurrentLocale() {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid != null) {
      // If box isn't open, we can't await it here since this is called in build
      // But we should have opened it in main() or during login
      if (Hive.isBoxOpen('settings_$uid')) {
        final box = Hive.box('settings_$uid');
        final lang = box.get('language', defaultValue: 'English');
        return getLocaleFromLang(lang);
      }
    }
    return locale;
  }

  // New method to update locale after login
  static Future<void> updateAppLocale() async {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid != null) {
      final box = await Hive.openBox('settings_$uid');
      final lang = box.get('language', defaultValue: 'English');
      Get.updateLocale(getLocaleFromLang(lang));
    }
  }

  // New method to reset to default on logout
  static void resetToDefault() {
    Get.updateLocale(locale);
  }
}
