// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5wwS0EtypY3xsx0OSZMGpEyMdr3HybI',
    appId: '1:818328957757:web:129bb8b51e406fd7d1cb54',
    messagingSenderId: '818328957757',
    projectId: 'birthdaycounter-40a17',
    authDomain: 'birthdaycounter-40a17.firebaseapp.com',
    storageBucket: 'birthdaycounter-40a17.firebasestorage.app',
    measurementId: 'G-C0XLWZ199L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpfSq6-J38S8eEwUsbcB6s9fvZhUafVJU',
    appId: '1:818328957757:android:ab259d7cbf976f55d1cb54',
    messagingSenderId: '818328957757',
    projectId: 'birthdaycounter-40a17',
    storageBucket: 'birthdaycounter-40a17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFlRLNTJYankYhhjVCcYgOd8N7ny8NA0',
    appId: '1:818328957757:ios:efde849369c665b8d1cb54',
    messagingSenderId: '818328957757',
    projectId: 'birthdaycounter-40a17',
    storageBucket: 'birthdaycounter-40a17.firebasestorage.app',
    androidClientId: '818328957757-nesur59kobcn19klfckh308d302nthfe.apps.googleusercontent.com',
    iosClientId: '818328957757-adue8akk16uk4tcsgfi5tmads65j9a08.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRFlRLNTJYankYhhjVCcYgOd8N7ny8NA0',
    appId: '1:818328957757:ios:efde849369c665b8d1cb54',
    messagingSenderId: '818328957757',
    projectId: 'birthdaycounter-40a17',
    storageBucket: 'birthdaycounter-40a17.firebasestorage.app',
    androidClientId: '818328957757-nesur59kobcn19klfckh308d302nthfe.apps.googleusercontent.com',
    iosClientId: '818328957757-adue8akk16uk4tcsgfi5tmads65j9a08.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq5wwS0EtypY3xsx0OSZMGpEyMdr3HybI',
    appId: '1:818328957757:web:5c9cc1fa705e7a09d1cb54',
    messagingSenderId: '818328957757',
    projectId: 'birthdaycounter-40a17',
    authDomain: 'birthdaycounter-40a17.firebaseapp.com',
    storageBucket: 'birthdaycounter-40a17.firebasestorage.app',
    measurementId: 'G-FTG0PNX33X',
  );
}
